describe("objects", function()
  local t, meta, is, mt, oid, td, mongo, job, auth, remote, simple, storage, cache, __storage
  setup(function()
    meta = require "meta"
    t = t or require "t"
    t.env.MONGO_HOST='127.0.0.1'
    t.env.MONGO_PORT=27015
    is = t.is
    mt = meta.mt

    td = require "testdata"
    mongo = (t.storage.mongo ^ t.def) ^ td.def
    oid = mongo.oid

    job = assert(t.def.job)
    auth = assert(td.def.auth)
    remote = assert(td.def.remote)
    simple = assert(td.def.simple)

    cache=meta.cache
    __storage = cache.storage
    storage=setmetatable({},{__index=function(_, self) return __storage[self][tostring(self)] end })
    assert.is_true(-job)
    meta.log.report=false
  end)
  it("mt", function()
    assert.equal(t.definer, meta.module(t.def).link.handler)

    assert.is_function(mt(remote).ping)
    assert.is_function(remote.ping)
    assert.def(simple)
    assert.truthy(meta.cache.loaded[simple])
    assert.factory(simple)
    assert.is_function(mt(simple).__imports._id)

    local item=simple({yes=true})
    assert.is_table(item)
    assert.def(item)
    assert.not_factory(item)
    assert.not_defroot(item)
    assert.defitem(item)

    assert.is_table(item.__imports)
    assert.is_table(item.__required or {})
    assert.is_table(item.__default)
  end)
  it("new", function()
    assert.is_nil(job())
    assert.is_nil(job(true))
    assert.is_nil(job(false))
    assert.is_nil(job(0))
    assert.is_nil(job(1))
    assert.is_nil(job(2))
    assert.is_nil(job(''))
    assert.is_nil(job(' '))
    assert.is_nil(job('1'))
    assert.is_nil(job('item'))

    assert.defitem(job({}))

    assert.equal(t.array(), job({''}))
    assert.equal(t.array(), job({true}))
    assert.equal(t.array(), job({false}))
    assert.equal(t.array(), job({1}))

    local i = job({done=true, message='some', created=0})
    assert.eq({done=true, message='some', created=0}, i)

    i = job('{"done":false, "message":"another", "created":2}')
    assert.eq(i, {done=false, message='another', created=2})
    assert.eq({done=false, message='another', created=2}, i)
    assert.is_table(mt(i))
  end)
  it("noneexistent", function()
    local o = td.def.noneexistent
    local id='66909d26cbade70b6b022b9a'
    assert.is_table(o)
    assert.is_nil(o/'any')
    assert.eq({_id=oid(id)}, o/id)
    assert.equal("y", o('{"x":"y"}').x)
  end)
  it("__add/__sub/__concat/__mod/__unm", function()
    assert.is_true(job*nil)
    assert.is_nil(job + nil)
    assert.is_nil(job + true)
    assert.is_nil(job + false)
    assert.is_nil(job + 0)
    assert.is_nil(job + 1)
    assert.is_nil(job + 2)
    assert.is_nil(job + '')
    assert.is_nil(job + ' ')
    assert.is_nil(job + '1')
    assert.is_nil(job + 'item')
    assert.is_nil(job + {''})
    assert.is_nil(job + {true})
    assert.is_nil(job + {false})
    assert.is_nil(job + {1})
    assert.equal(0, job % {})

    assert.is_true(job + {_id='66ef5a258aa5f11c0c094b25', n=1})
    assert.equal(1, tonumber(storage[job]))

    assert.equal(1, job % {})
    assert.is_true(job + {_id='66ef5a258aa5f11c0c094b26', n=2, done=true, message='some', created=0})
    assert.equal(2, job % {})
    assert.is_nil(job['66909d26cbade70b6b022b9a'])
    assert.is_true(job + job({_id='66909d26cbade70b6b022b9a', n=3, done=true, message='some', created=0}))
    assert.equal(3, job % {})
    assert.is_true(job + job({_id='66ef5a258aa5f11c0c094b27', n=4}))
    assert.is_true(job + job({_id='66ef5a258aa5f11c0c094b28', n=5}))
    assert.equal(5, job % {})
    assert.eq({_id='66909d26cbade70b6b022b9a', n=3, done=true, message='some', created=0}, job['66909d26cbade70b6b022b9a'])
    assert.eq({_id='66ef5a258aa5f11c0c094b28', n=5}, job['66ef5a258aa5f11c0c094b28'])

    assert.is_true(job - '66ef5a258aa5f11c0c094b25')
    assert.equal(4, job % {})
    assert.equal('userdata', type((job/{'66909d26cbade70b6b022b9a','66ef5a258aa5f11c0c094b26'})[1]._id))

    assert.equal(2, (job - {'66909d26cbade70b6b022b9a','66ef5a258aa5f11c0c094b26'}).nRemoved)

    assert.equal(2, job % {})
    assert.is_true(job + {_id='66ef5a258aa5f11c0c094b25', n=1})
    assert.equal(3, job % {})
    assert.equal(2, (job - job({{_id='66ef5a258aa5f11c0c094b27', n=4},{_id='66ef5a258aa5f11c0c094b25', n=1}})).nRemoved)
    assert.equal(1, job % {})
    assert.is_true(job - job['66ef5a258aa5f11c0c094b28'])
    assert.equal(0, job % {})
    assert.is_true(job*nil)

    assert.is_true(job + '{"_id":"66ef5a258aa5f11c0c094b25", "n":1}')
    assert.equal(1, job % {})
    assert.is_true(job + job('{"_id":"66ef5a258aa5f11c0c094b26", "n":2}'))
    assert.equal(2, job % {})
    assert.is_true(job*nil)
    assert.equal(0, job % {})
    assert.equal(2, (job + '[{"_id":"66ef5a258aa5f11c0c094b25", "n":1},{"_id":"66ef5a258aa5f11c0c094b26", "n":2}]').nInserted)
    assert.equal(2, job % {})
    assert.equal(2, (job + job('[{"_id":"66ef5a258aa5f11c0c094b27", "n":3},{"_id":"66ef5a258aa5f11c0c094b28", "n":4}]')).nInserted)
    assert.equal(4, job % {})
    assert.is_true(job*nil)

    assert.is_true(job .. '{"_id":"66ef5a258aa5f11c0c094b25", "n":1}')
    assert.equal(1, job % {})
    assert.is_true(job .. job('{"_id":"66ef5a258aa5f11c0c094b26", "n":2}'))
    assert.equal(2, job % {})
    assert.is_true(job*nil)
    assert.equal(0, job % {})
    assert.equal(2, (job .. '[{"_id":"66ef5a258aa5f11c0c094b25", "n":1},{"_id":"66ef5a258aa5f11c0c094b26", "n":2}]').nInserted)
    assert.equal(2, job % {})
    assert.equal(2, (job .. job('[{"_id":"66ef5a258aa5f11c0c094b27", "n":3},{"_id":"66ef5a258aa5f11c0c094b28", "n":4}]')).nInserted)
    assert.equal(4, job % {})

    assert.is_true(job - job('{"_id":"66ef5a258aa5f11c0c094b26", "n":2}')/true)
    assert.is_nil(job['66ef5a258aa5f11c0c094b26'])
    assert.equal(3, job % {})
    assert.is_true(job - job/'66ef5a258aa5f11c0c094b25')
    assert.equal(2, job % {})
    assert.is_true(-job['66ef5a258aa5f11c0c094b28'])
    assert.equal(1, job % {})

    assert.truthy(job['66ef5a258aa5f11c0c094b27'])
    assert.equal('userdata', type(job['66ef5a258aa5f11c0c094b27']._id))

    assert.equal('userdata', type(job({_id='66ef5a258aa5f11c0c094b27', n=3})._id))
    assert.equal(job['66ef5a258aa5f11c0c094b27']._id, job({_id='66ef5a258aa5f11c0c094b27', n=3})._id)
    assert.equal(job['66ef5a258aa5f11c0c094b27'], job({_id='66ef5a258aa5f11c0c094b27', n=3}))

    assert.eq({['$ref']='job',['$id']={_id=oid('66ef5a258aa5f11c0c094b27')}}, job['66ef5a258aa5f11c0c094b27'].ref)

    assert.is_true(job*nil)
    assert.equal(0, job % {})
  end)
  it("data", function()
    local o = assert(td.def.data)
    assert.equal(0, o % {})
    local item = o({_id='66ef5a258aa5f11c0c094b25', n=1})
    assert.is_true(o + item)
    assert.equal(1, o % {})
    assert.eq(item, o['66ef5a258aa5f11c0c094b25'])
    assert.is_true(toboolean(item))
    assert.is_true(toboolean(o['66ef5a258aa5f11c0c094b25']))
    assert.is_true(o*nil)
    assert.equal(0, o % {})
  end)
  it("__concat", function()
    assert.is_true(job*nil)
    assert.is_nil(job .. nil)
    assert.is_nil(job .. true)
    assert.is_nil(job .. false)
    assert.is_nil(job .. 0)
    assert.is_nil(job .. 1)
    assert.is_nil(job .. 2)
    assert.is_nil(job .. '')
    assert.is_nil(job .. ' ')
    assert.is_nil(job .. '1')
    assert.is_nil(job .. 'item')
    assert.is_nil(job .. {''})
    assert.is_nil(job .. {true})
    assert.is_nil(job .. {false})
    assert.is_nil(job .. {1})
    assert.is_nil(job .. {})
    assert.equal(0, job % {})

    assert.equal(1, (job .. {job({done=true, message='some', created=0})}).nInserted)
    assert.equal(1, job % {})

    assert.equal(1, (job .. {{done=true, message='some', created=0}}).nInserted)
    assert.equal(2, job % {})

    local tb = {{_id='66ef5a258aa5f11c0c094b27', n=3},'{"_id":"66ef5a258aa5f11c0c094b26", "n":2}',{_id='66909d26cbade70b6b022b9a', n=4, done=true, message='some', created=0}}
    assert.is_true(is.bulk(tb))
    assert.equal(3, tonumber(tb))

    local add = job + tb
    assert.equal(3, add.nInserted)
    assert.equal(3, add.nInserted + add.nUpserted)
    assert.equal(5, tonumber(job))
    assert.is_true(job*nil)
    assert.equal(0, job % {})
  end)
  it("__sub", function()
    assert.ok(job*nil)
    assert.is_nil(job - nil)
    assert.is_nil(job - true)
    assert.is_nil(job - false)
    assert.is_nil(job - 0)
    assert.is_nil(job - 1)
    assert.is_nil(job - 2)
    assert.is_nil(job - ' ')
    assert.is_nil(job - '1')
    assert.is_nil(job - 'item')
    assert.is_nil(job - {''})
    assert.is_nil(job - {true})
    assert.is_nil(job - {false})
    assert.is_nil(job - {1})

    assert.is_nil(job - '')
    assert.equal(0, job % {})

    assert.is_true(job + {})
    assert.equal(1, job % {})
    assert.is_true(job + {})
    assert.equal(2, job % {})
    assert.is_true(job - {})
    assert.equal(0, job % {})
  end)
  describe("__div", function()
    describe("auth", function()
      it("defroot", function()
        local id='66909d26cbade70b6b022b9a'
        local token='95687c9a1a88dd2d552438573dd018748dfff0222c76f085515be2dc1db2afa7'

        assert.equal(nil, auth/nil)
        assert.equal(nil, auth/true)
        assert.equal(nil, auth/false)
        assert.equal(nil, auth/0)
        assert.equal(nil, auth/1)
        assert.equal(nil, auth/2)
        assert.equal(nil, auth/' ')
        assert.equal(nil, auth/'1')
        assert.equal(nil, auth/'item')
        assert.equal(nil, auth/{''})
        assert.equal(nil, auth/{true})
        assert.equal(nil, auth/{false})
        assert.equal(nil, auth/{1})
        assert.equal(nil, auth/'')
        assert.eq({_id=oid(id)}, auth/id)
        assert.eq({token=token}, auth/token)
      end)
      it("defitem", function()
        local id='66909d26cbade70b6b022b9a'
        local token='95687c9a1a88dd2d552438573dd018748dfff0222c76f085515be2dc1db2afa7'
        local item=auth({_id=id, role='root', token=token})

        assert.eq({_id=oid(id)}, item/true)
        assert.equal('_id', item/false)
        assert.equal(nil, item/nil)
        assert.equal(nil, item/0)
        assert.equal(nil, item/1)
        assert.equal(nil, item/2)
        assert.equal(nil, item/' ')
        assert.equal(nil, item/'1')
        assert.equal(nil, item/'item')
        assert.equal(nil, item/{''})
        assert.equal(nil, item/{1})
        assert.equal(nil, item/'')
        assert.equal(nil, item/id)
        assert.equal(nil, item/token)
        assert.eq({_id=oid(id)}, item/item)
        assert.eq({_id=oid(id)}, auth/item)
      end)
    end)
    it("auth object", function()
      local id='66909d26cbade70b6b022b9a'
      local token='95687c9a1a88dd2d552438573dd018748dfff0222c76f085515be2dc1db2afa7'

      assert.is_table(auth.__id)
      assert.eq({_id=oid(id)}, auth/id)
      assert.eq({token=token}, auth/token)

      local o=job({_id=id, done=true, message='some', created=0})
      assert.equal('_id', o/false)
      assert.equal('mongo.ObjectID', t.type(o._id))
      assert.equal('mongo.ObjectID', t.type((o/true)._id))
      assert.same({_id=oid(id)}, o/true)

      o=auth({role='root', token=token})
      assert.eq({role='root', token=token}, o)
      assert.is_nil(o._id)
      assert.equal(token, o.token)
      assert.eq('token', o/false)
      assert.eq({token=token}, o/true)
    end)
  end)
end)